### ISSUE TITLE
Plivo numbers.buy

### ISSUE THREAD

**Issue by apex2060** [plivo/plivo-node#144]
I am getting an error when attempting to purchase a new number through the node library:
All variables exist and are correct.  I've tried just the number 

let plivo = new Plivo.Client(process.env.plivoId, process.env.plivoToken);
plivo.numbers.buy(number.id).then(r=>{

let plivo = new Plivo.Client(process.env.plivoId, process.env.plivoToken);
plivo.numbers.buy(number.id, process.env.plivoApp).then(r=>{

returns an error: 
2020-02-09T01:06:16.182390+00:00 app[web.1]: Error: {"api_id":"5f595aa6-4ad8-11ea-a859-0242ac110003","error":"not found"}
2020-02-09T01:06:16.182401+00:00 app[web.1]:     at ResourceNotFoundError.PlivoRestError (/app/node_modules/plivo/dist/utils/exceptions.js:19:113)
2020-02-09T01:06:16.182401+00:00 app[web.1]:     at new ResourceNotFoundError (/app/node_modules/plivo/dist/utils/exceptions.js:31:127)
2020-02-09T01:06:16.182402+00:00 app[web.1]:     at Request._callback (/app/node_modules/plivo/dist/rest/request.js:80:20)
2020-02-09T01:06:16.182402+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:185:22)
2020-02-09T01:06:16.182402+00:00 app[web.1]:     at Request.emit (events.js:223:5)
2020-02-09T01:06:16.182403+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
2020-02-09T01:06:16.182403+00:00 app[web.1]:     at Request.emit (events.js:223:5)
2020-02-09T01:06:16.182403+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
2020-02-09T01:06:16.182403+00:00 app[web.1]:     at Object.onceWrapper (events.js:312:28)
2020-02-09T01:06:16.182404+00:00 app[web.1]:     at IncomingMessage.emit (events.js:228:7)
2020-02-09T01:06:16.182404+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1185:12)
2020-02-09T01:06:16.182404+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by nixonsam** [comment]
@apex2060 Looks like you're using the legacy SDK's method 'plivo.numbers.buy'. Please use the latest SDK.
You can find the code snippet [here](https://www.plivo.com/docs/numbers/api/phone-number#buy-a-phone-number) and you can install the SDK by referring to the instructions [here](https://www.plivo.com/docs/sdk/server/node-sdk)

Feel free to contact our [support team](https://support.plivo.com/support/home)
