### ISSUE TITLE
API for Getting List of Conference Gives Error

### ISSUE THREAD

**Issue by dev-wilco** [plivo/plivo-node#149]
When the [list all conference](https://www.plivo.com/docs/voice/detailed-reference/api/conference#list-all-conferences) API is called, below added error occurs.

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at E:\wsple204\rcm\back-end\node_modules\plivo\dist\rest\request.js:60:16
    at E:\wsple204\rcm\back-end\node_modules\plivo\dist\rest\utils.js:66:12
    at E:\wsple204\rcm\back-end\node_modules\plivo\dist\resources\conferences.js:385:9
    at new Promise (<anonymous>)
    at ConferenceInterface.list (E:\wsple204\rcm\back-end\node_modules\plivo\dist\resources\conferences.js:384:14)
    at E:\wsple204\rcm\back-end\routes\routes.js:542:28
    at Layer.handle [as handle_request] (E:\wsple204\rcm\back-end\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\wsple204\rcm\back-end\node_modules\express\lib\router\index.js:317:13)
    at E:\wsple204\rcm\back-end\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\wsple204\rcm\back-end\node_modules\express\lib\router\index.js:335:12)

I encountered this issue with Plivo Node SDK @4.5

**Comment by nixonsam** [comment]
@dev-wilco the response of List Conferences API was fixed in https://github.com/plivo/plivo-node/releases/tag/v4.5.2.
