### ISSUE TITLE
Plivo Numbers Buy

### ISSUE THREAD

**Issue by Brando753** [plivo/plivo-node#171]
Issue #144 is very much an issue with the current library, using the latest version of the plivo library `"plivo": "^4.12.0",` I encounter the exact same issue reported before.

This is a snippet from the plivo docs on how to use the numbers buy call:
```js
// Example for PhoneNumber create

var plivo = require('plivo');

(function main() {
    'use strict';
    
    // As the auth_id and auth_token are unspecified, Plivo will fetch them from the PLIVO_AUTH_ID and PLIVO_AUTH_TOKEN environment variables.
    var client = new plivo.Client();
    client.numbers.buy(
        "10123456789", // number
    ).then(function (response) {
        console.log(response);
    }, function (err) {
        console.error(err);
    });
})();
```

Which is very different from the legacy API which was 
```js
var plivo = require('plivo');
var p = plivo.RestAPI({
  authId: 'Your AUTH_ID',
  authToken: 'Your AUTH_TOKEN'
});

// Buy a phone number
var params = { 
    'number' : '444444444444' // Phone number to buy
};

p.buy_phone_number(params, function (status, response) {
    console.log('Status: ', status);
    console.log('API Response:\n', response);
});
```
When I do as the latest API docs call I get the same error that was reported before:
```js
const client = new plivo.Client();
let response
client.numbers.buy("14809552987").then((res) => {response = res})
(node:2331764) UnhandledPromiseRejectionWarning: Error: {"api_id":"f6a23448-56d8-11eb-8cee-0242ac110005","error":"not found"}
    at ResourceNotFoundError.PlivoRestError (/home/anderson/workspace/backend/node_modules/plivo/dist/utils/exceptions.js:19:113)
    at new ResourceNotFoundError (/home/anderson/workspace/backend/node_modules/plivo/dist/utils/exceptions.js:31:127)
    at Request._callback (/home/anderson/workspace/backend/node_modules/plivo/dist/rest/request.js:221:22)
    at Request.self.callback (/home/anderson/workspace/backend/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:506:15)
    at Request.<anonymous> (/home/anderson/workspace/backend/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:506:15)
    at IncomingMessage.<anonymous> (/home/anderson/workspace/backend/node_modules/request/request.js:1076:12)
(node:2331764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2331764) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

The numbers section of this library seems to be riddled with problems and seems to not follow any of the API docs on implementation.

**Comment by Brando753** [comment]
Determined the cause for me was the API keys I used were authorized to search numbers, send SMS, etc but were not authorized to purchase numbers. Advise a custom exception be raised on 401 status codes of UnauthorizedRequest. Would have saved me some time in debugging this.

**Comment by huzaif-plivo** [comment]
@Brando753 We have fixed this in our [latest release](https://github.com/plivo/plivo-node/releases/tag/4.14.1), please feel free to contact our [support team](https://support.plivo.com/hc/en-us) for any issues.
