### ISSUE TITLE
Sometimes i get errors from you library

### ISSUE THREAD

**Issue by roysG** [plivo/plivo-node#204]
(node:18) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at /app/code/node_modules/plivo/dist/rest/axios.js:233:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)

**Comment by huzaif-plivo** [comment]
@roysG The issue has been fixed in our [latest release](https://github.com/plivo/plivo-node/releases/tag/v4.22.1). Feel free to contact our [support-team](https://support.plivo.com/hc/en-us) for any concerns.

**Comment by saltire** [comment]
I don't think this issue has been fixed. I recently got this error running v4.23.1.

I notice you added in some checks like this:
```
if (error.response == undefined) {
  reject(error.stack);
}
```
I think there should also be a `return` statement in there, or the rest should be in an `else` block, because `reject` doesn't stop the code from executing and it will still fail checking for `error.response.status` below.

**Comment by narayana-plivo** [comment]
@saltire It would be great, if you share the stack trace.

**Comment by saltire** [comment]
@narayana-plivo It's very much like the OP's:
```
Uncaught exception: TypeError: Cannot read properties of undefined (reading 'status')
    at /app/node_modules/plivo/dist/rest/axios.js:292:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
```
